---
name: push

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle-main:
    runs-on: ubuntu-latest
    name: checkstyle-main

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: checkStyle with gradle
        run: ./gradlew checkstyleMain

  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '23'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: build with gradle
        run: ./gradlew build